
services:
  biblioteca-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/biblioteca
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQLDialect
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - biblioteca-network

  mysql-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: biblioteca
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - biblioteca-network

networks:
  biblioteca-network:
    driver: bridge

volumes:
  mysql_data: